server:
  Port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: hijkl
#    driver-class-name: com.postgresql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application: 
    name: HOTEL-SERVICE
  config:
    import: configserver:http://localhost:8086

